# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images/products'
        # aws.storage:
        #     adapter: 'aws'
        #     options:
        #         client: 'aws_client_service' # The service ID of the Aws\S3\S3Client instance
        #         bucket: 'product'
        #         prefix: 'optional/path/prefix'
        #         streamReads: true
