# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        default_adapter:

                  awss3v3:
                      client: Aws\S3\S3Client
                      bucket: "%env(AWS_ACCESS_BUCKET)%"
                      prefix: ""
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
