# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    # mappings:
    #     products:
    #         uri_prefix: /images/products
    #         upload_destination: aws.storage
    #         # upload_destination: '%kernel.project_dir%/public/images/products'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #     type:
    #         uri_prefix: /images/type
    #         upload_destination: '%kernel.project_dir%/public/images/type'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
